-- ⚠️ DEPRECATED: This file is no longer used.
-- 
-- The project now uses separate PostgreSQL containers for each microservice
-- following best practices for microservices architecture.
--
-- Each service has its own dedicated database:
-- - postgres-auth:       auth_db
-- - postgres-pricing:    pricing_db
-- - postgres-inventory:  inventory_db
-- - postgres-finance:    finance_db
-- - postgres-notification: notification_db
--
-- See DATABASE_ARCHITECTURE.md for details on the new database setup.
